spring:
  application:
    name: common
  profiles:
    active: dev
  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: jdbc:mysql://${spring.datasource.address}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 192.168.226.128
    port: 5672
    virtual-host: /s-pay-mall
    username: s-pay-mall
    password: 123456
    publisher-confirm-type: correlated #开启publisher confirm机制，并设置confirm类型
    publisher-returns: true #开启publisherreturn机制
    listener:
      simple:
        acknowledge-mode: auto


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    xin:
      eason:
        dao: ${logging-level.dao}
        common: ${logging-level.common}
        domain: ${logging-level.domain}
        service: ${logging-level.service}
        web: ${logging-level.web}

wechat:
  grant-type: ${wechat.grant-type}
  appid: ${wechat.appid}
  secret: ${wechat.secret}
  originalid: ${wechat.originalid}
  token: ${wechat.token}

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app-id: 9021000143682740
  merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCHx8CXZpwHqwZy/LnN6P1OEKBAfa5Zh4IbVQ7KyWRRbkOgtBrIP6g9yk0mQnabr1eMkxFPjWZl7vyCiGQZTqaBu/xYdy4QJq5iY9Is9o7vezApMvBrBt+7NVfAdsGZFrbwmedLLkdJaJEW3W+7ab4Hf7sux5YEYbMc/pt2zYKjKXENh8E0RbwDSwQouNwkYeo2nJOdfAwArzgMp4uYykvfLFD2u7t6XQWCyb1rhxhqCXoM5HVxMjZYf1sEP/z2J7rYm89NyE6LO46wGELyBxF/JzSNbJAhN4HLD2LSjWl9zCe63zPPZN7AsnrGSUVLg/DuE3UVZfvYar4vHkJZyQpHAgMBAAECggEAYpZOJ2AQkJzEXP9VZcXzDhiSUuEuk8EJXhEfYWxjE6EtJ2U+QQG/hcX6yHnfpuDkf6RVIF75569j1t9zVtC9o1s8OXunjYCYg8YY2B7Z39ahPHjJCdz+2+46XfucTCyq/f2xa+wZRJrRJjn4I6r+mHFNFwVBzsKli7ruZI+JeC/TGKVRea3AwFJW2+asUxJnjcM5zcWzDrETv9i9WD/Zk4nDegQuJU7UmKnlxv0Vn0Ru1s8OxcV9gPU4s+EkibL0xgPiUqfnCqqC4TZ0Sn3WNTlDodoo5ehoDt218TcLWiFwNK4mfpw609vlo6TdqE4k6SLD0zwS68HTbGBkgPwzSQKBgQC/cE91Rqf4DyquE4Bif9X49Uud7l7E7OS43fLXzg/j6QbvNAFAWhP1OqFUZNPNU4rT1DZZsOJF9cx4dkrP/6OkWau7vp/5ei1cZFoYKRSdNMvDO7HMacrY3fy6UbDJo+R5xKCrbDxXmyYm6WMzbtxfAq4wpQOnIuhbqL3JMgq86wKBgQC1kjilSDYvWIDE38j8xcNmXj1POIjSWqMx1Nf6GIZqjBB7KPwrAx8TDMGdevRHUJCCg5m0dCX65/bkuNjAbOb3h5RliM7guXER2fvzs3QznnaS8VLlrHmOOBMW8lbIE0r+vVm4uJ5gYQd6+LGTtYBJAqTFcT1zgnH28Am8EVfhFQKBgBARoEnKxXyX4VA9SNB7xH0iMdeu03uaGtS9pI2iuUi7HZ7kcZpyNSynYDVSRUj90zBWpr0+kK+ooyIVY9AzuAuqjzSyGoF5VOdlcP6ILDfJ37SihRkQZDtx3q3Q/5LdU+c4rvfUnPgJiNlJS89cZdj/w5lHsJfN4U0YS93genBDAoGBAIZIAYSbBxe0yGbRaf8m8v++KnFwSh/n0FGGK8RWZvJda8Lp6LSWtmCMSpSA3i/vsTAUy5PdYklRTBKTchm9cIMXzfPZXcZs3uZo5CCzUvjp9J9vwfMBv1QivFt4Fh4ZxpjmyHgIcXitya50RkALNzjHr7wlp2DJ1CbgFxLzcJ6RAoGAfjSdRZmOYNpkmh/ZJ573GgARku6iw1g8PtcmIriaroYcqTwwdOtNl3eXxsDkG9GK3CQcmgFtUV2Vdk5X2OvHEkWVampYr4MVy8QqpGQiyashKQCpK7XcSy66xDye3Eqc74ftADeyf/OapHpYWRm16T3XsEAlrZOP052guElgrV4=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp9HohP+UIcNpz4ZNA3pxiLUZMgH621iQx56NJpGEvCkW1pL+NYoRSDNlqq18WQqETYEyKZ9QgdcQB4BTmVrCqibPnuI9czsLdFPbuT9mf0nC8KP5hkLdL5AI4LF6PI4oWGv4ryiTUeeVvfa6WhNhJ1v+mGCqXhObufHRCZNDCEcjKLn9XlaDskW74bJ6ZcbkXCXTdeqvBLZG8LY95xZvnMuvPvd/ek/2c4L0TY8dFGB5o9v2WD4kVo4PZLVggTcaP0OYmcVyLjKyoAx3luo9Wt820xFq5NTf+R00jxVMpBuwBSPT7lMVvaMKNbMSR/A0asGLSXKLAQscHreP+YAs8wIDAQAB
  notify-url: http://eason.nat300.top/api/v1/alipay/alipay_notify_url
  return-url: https://gaga.plus
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  format: json
  charset: utf-8
  sign-type: RSA2

s-pay-mall:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
