server:
  port: 8081

spring:
  application:
    name: common
  profiles:
    active: dev
  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: jdbc:mysql://${spring.datasource.address}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: ${spring.rabbitmq.host}
    port: ${spring.rabbitmq.port}
    virtual-host: ${spring.rabbitmq.virtual-host}
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
    publisher-confirm-type: correlated #开启publisher confirm机制，并设置confirm类型
    publisher-returns: true #开启publisherreturn机制
    listener:
      simple:
        acknowledge-mode: auto


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    xin:
      eason:
        dao: ${logging-level.dao}
        common: ${logging-level.common}
        domain: ${logging-level.domain}
        service: ${logging-level.service}
        web: ${logging-level.web}

wechat:
  grant-type: ${wechat.grant-type}
  appid: ${wechat.appid}
  secret: ${wechat.secret}
  originalid: ${wechat.originalid}
  token: ${wechat.token}

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app-id: 9021000143682740
  merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCFZEQknIh614crOOzzRDKx970+ai+O0FdgYrc1sspqrUh8dKtXHNzvTKepavLOwfUG22LBjR/ZhiniDpl2MQSlbF+xWBYOZRjTywIbLiAW6I2mo7PxwX0Fv9NvOdzz0jE9osUqY+7OVKVd9AmS+Hrxa75Xbvec06lrAPHwwh5SBZ6ZUUvPXyGpLb+OqX4f8h0FK6yatBTrga7VHyEBZJTAQLgEA1AVZw9QfBqRjYo/6hdFGBr4PJb1nn5igVrAaYqImCjtSyRjYrYjwrhXLHsI0S4o4/ciS/MGkFuDg+CKnTiEjszOhzmstAVHeggxJrqDtf0/5Jx/OfTsjUN19/2/AgMBAAECggEAO+WOA7KWRjLJa0sgewvAh9FqlMAxortCwPESu3YRFl3BEsGAvpkjTADruFNhvB2z3OReL/MivhZUcEGF/2B7aZyES6n2HXif8VpTE8led2rtUEpp3sC3VwGP+33MDV/w5HBWgHZnIRc5Ojr+oZQaAJYU3kXhwfX5OScvfKBt5P4dUMpuHVlH1+arRnzdj8cA5Mwa+NPd0iy6SfH5P2DzXnaVBhGByXSBFgL7x+YupF4SeueS6fMRgElOBmzbqFjr7aS8MfmxqIYNhmgQZFOHnNeLM2bMcJGR0qv7N2ytEfE3d8sPcYXmo/YNz3d2V0fmglCMTJpv0utJMQInasM8wQKBgQDwFHWOf/JQn8NcMHCQjo40BBPdMpkw+aEsP+uMSGos/urbu63NiL8hzqRIUuPwCq2Vq2/51wgbGEUHWQSuV2O0tQ60PWT00C/Bfvmhs+9GpwUOfV5jN0t7CcqAK6rpdCDgNcmiuBywwZvPM+ZRem0KdhK2/Zj6h18HFQCY00KJqQKBgQCOPLEoYcSrB0VoBVC6g/Qr/WVW5bJfYtcKlIm+rP0qRj3+jT6Ug3wG4xCPKpFTr/5DyulA0PstpaZzPx5bJjU54Svn8f8jaWA1XJpmzlpdZ3oAvq1r6DxDehhg3RXa8wIFnynfemkSa0eonUHAZfFHBGzCiwgfibsonHhgViH9JwKBgQCmazg2CGD7HFP6sqVEv1y5l94BJhLkzRW5K7Hm80eOW0KIAKfw4orDL4/XhoX0niJHrqgXQsSeq4smFcHV7EP0PtGrhSdXQHzqH0+BlM4XZq1tpt/n3KuY5WeWwy5dV592bDKSdheFOx/7WJmd/0RYzRIaAN6rQ21O5nMcfM0RyQKBgEeIMFQtrxmQI5Cns6zJdb+1xQRJqkYcUCdrAkcZeoyLHNxqrkFEStiv0wEdGE8tIEN5xYqqTtfrCeXFpX+TnIsKOemBI53sfcz4UFJJjtqQkqPTQSYWelA5FA+KwFYHhknLfOR+DF+OAlDDHXEkE45ypDvGbgRmYPCQmF1ik99bAoGBAMY/rQwz8/AObRQ5Fa9zUn45IkS1Yvd4EhJY8QdCCy5GJHPM2wK51JWRwmkOKNZsS5Cv804fNmjvwKdRcTI3qK20ukZNk4YTrVWv0sPZR5y4GlztcNwubChw7k/y/PivWWm4SIvL1LlTECJqvLncyFieuxIBcqD3Agt8qL3CSA6P
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp9HohP+UIcNpz4ZNA3pxiLUZMgH621iQx56NJpGEvCkW1pL+NYoRSDNlqq18WQqETYEyKZ9QgdcQB4BTmVrCqibPnuI9czsLdFPbuT9mf0nC8KP5hkLdL5AI4LF6PI4oWGv4ryiTUeeVvfa6WhNhJ1v+mGCqXhObufHRCZNDCEcjKLn9XlaDskW74bJ6ZcbkXCXTdeqvBLZG8LY95xZvnMuvPvd/ek/2c4L0TY8dFGB5o9v2WD4kVo4PZLVggTcaP0OYmcVyLjKyoAx3luo9Wt820xFq5NTf+R00jxVMpBuwBSPT7lMVvaMKNbMSR/A0asGLSXKLAQscHreP+YAs8wIDAQAB
  notify-url: http://eason.nat300.top/api/v1/alipay/alipay_notify_url
  return-url: https://gaga.plus
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  format: json
  charset: utf-8
  sign-type: RSA2

s-pay-mall:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # SC 渠道配置 - 拼团对接渠道值、回调通知
    group-buy-market:
      api-url: http://127.0.0.1:8080    # 拼团平台地址
      notify-url: http://127.0.0.1:8081/api/v1/alipay/group_buy_notify  # 拼团平台回调本系统地址
      source: s01
      chanel: c01

