# 命令执行 docker-compose -f docker-compose-environment-aliyun.yml up -d
# docker 代理和使用文档；https://bugstack.cn/md/road-map/docker.html
version: '3.9'

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - /root/docker/mysql/data:/var/lib/mysql
      - /root/docker/mysql/conf:/etc/mysql/conf.d
      - /root/docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - s-pay-mall

  nginx:
    image: nginx:latest
    container_name: nginx          # 容器名称
    restart: always                # 自动重启
    environment:
      - TZ=Asia/Shanghai           # 设置时区
    ports:
      - "9999:80"                    # 映射端口
    deploy:
      resources:
        limits:
          cpus: "0.5"              # 限制 CPU 核心数
          memory: "512M"           # 限制内存大小
    volumes:
      - /root/docker/nginx/html:/usr/share/nginx/html        # 数据持久化
      - /root/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf  # 配置持久化
      - /root/docker/nginx/log:/var/log/nginx
    networks:
      - s-pay-mall

networks:
  s-pay-mall:
    name: s-pay-mall
    driver: bridge