# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
version: '3.9'
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名
services:
  s-pay-mall-ddd-eason:
    image: s-pay-mall-ddd:1.0-SPANSHOT
    container_name: s-pay-mall-ddd-eason
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - TZ=PRC
      - SERVER_PORT=8080
    volumes:
      - /root/docker/s-pay-mall/log:/data/log
    networks:
      - s-pay-mall

networks:
  s-pay-mall:
    name: s-pay-mall
    driver: bridge
